name: ci

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3
        with:
          runtime: node@24
          cache: true
          install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🚧 Set up project
        run: pnpm dev:prepare

      - name: 🔠 Lint project
        run: pnpm lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3
        with:
          runtime: node@24
          cache: true
          install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🚧 Set up project
        run: pnpm dev:prepare

      - name: 🧪 Test project
        run: pnpm test -- --coverage

      - name: 💪 Test types
        run: pnpm test:types

      - name: 🛠 Build project
        run: pnpm build

      - name: 🏁 Benchmark project
        uses: CodSpeedHQ/action@f842b9a3ffe213dbb81768fd7f7eeb4dfcf1c369 # v5.4.2
        with:
          run: pnpm vitest bench
          token: ${{ secrets.CODSPEED_TOKEN }}

      - name: 🟩 Coverage
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7
